    $(document).ready(function()
    {
        $('#enviar').click(function()
        {
            var tmp = {
					'ip': $('#ip').val(),
					'cliente': $('#cliente').val(),
					'javascript': $('#javascript').val(),
					'action_type': $('#action_type').val(),
					'transaction_id': $('#transaction_id').val(),
					'affiliate_id': $('#affiliate_id').val(),
					'affiliate_name': $('#affiliate_name').val(),
					'user_order_memo': $('#user_order_memo').val(),
					'run_email_api': $('#run_email_api').val(),
					'email': $('#email').val(),
					'email_domain': $('#email_domain').val(),
					'password_hash': $('#password_hash').val(),
					'user_fullname': $('#user_fullname').val(),
					'user_name': $('#user_name').val(),
					'user_id': $('#user_id').val(),
					'user_created': $('#user_created').val(),
					'user_country': $('#user_country').val(),
					'user_city': $('#user_city').val(),
					'user_region': $('#user_region').val(),
					'user_zip': $('#user_zip').val(),
					'user_street': $('#user_street').val(),
					'user_street2': $('#user_street2').val(),
					'device_id': $('#device_id').val(),
					'payment_mode': $('#payment_mode').val(),
					'card_fullname': $('#card_fullname').val(),
					'card_bin': $('#card_bin').val(),
					'card_hash': $('#card_hash').val(),
					'card_last': $('#card_last').val(),
					'avs_result': $('#avs_result').val(),
					'cvv_result': $('#cvv_result').val(),
					'phone_number': $('#phone_number').val(),
					'transaction_type': $('#transaction_type').val(),
					'transaction_amount': $('#transaction_amount').val(),
					'transaction_currency': $('#transaction_currency').val(),
					'item_id': $('#item_id').val(),
					'item_quantity': $('#item_quantity').val(),
					'item_name': $('#item_name').val(),
					'item_price': $('#item_price').val(),
					'item_store': $('#item_store').val(),
					'item_store_country': $('#item_store_country').val(),
					'item_categories': $('#item_categories').val(),
					'item_url': $('#item_url').val(),
					'item_user_label': $('#item_user_label').val(),
					'item_id2': $('#item_id2').val(),
					'item_quantity2': $('#item_quantity2').val(),
					'item_name2': $('#item_name2').val(),
					'item_price2': $('#item_price2').val(),
					'item_store2': $('#item_store2').val(),
					'item_store_country2': $('#item_store_country2').val(),
					'item_categories2': $('#item_categories2').val(),
					'item_url2': $('#item_url2').val(),
					'item_user_label2': $('#item_user_label2').val(),
					'item_id3': $('#item_id3').val(),
					'item_quantity3': $('#item_quantity3').val(),
					'item_name3': $('#item_name3').val(),
					'item_price3': $('#item_price3').val(),
					'item_store3': $('#item_store3').val(),
					'item_store_country3': $('#item_store_country3').val(),
					'item_categories3': $('#item_categories3').val(),
					'item_url3': $('#item_url3').val(),
					'item_user_label3': $('#item_user_label3').val(),
					'shipping_country': $('#shipping_country').val(),
					'shipping_city': $('#shipping_city').val(),
					'shipping_region': $('#shipping_region').val(),
					'shipping_zip': $('#shipping_zip').val(),
					'shipping_street': $('#shipping_street').val(),
					'shipping_street2': $('#shipping_street2').val(),
					'shipping_phone': $('#shipping_phone').val(),
					'shipping_fullname': $('#shipping_fullname').val(),
					'shipping_method': $('#shipping_method').val(),
					'billing_country': $('#billing_country').val(),
					'billing_city': $('#billing_city').val(),
					'billing_region': $('#billing_region').val(),
					'billing_zip': $('#billing_zip').val(),
					'billing_street': $('#billing_street').val(),
					'billing_street2': $('#billing_street2').val(),
					'billing_phone': $('#billing_phone').val(),
					'discount_code': $('#discount_code').val(),
					'gift': $('#gift').val(),
					'gift_message': $('#gift_message').val(),
					'merchant_id': $('#merchant_id').val(),
					'merchant_created_at': $('#merchant_created_at').val(),
					'merchant_country': $('#merchant_country').val(),
					'details_url': $('#details_url').val(),
					'user_label': $('#user_label').val(),
					'is_intangible_item': $('#is_intangible_item').val(),
					'is_pay_on_delivery': $('#is_pay_on_delivery').val(),
					'departure_airport': $('#departure_airport').val(),
					'days_to_board': $('#days_to_board').val(),
					'is_pay_on_delivery2': $('#is_pay_on_delivery2').val(),
					'arrival_airport': $('#arrival_airport').val()
					};

            $.ajax({
              type: 'POST',
              url: 'http://45.32.171.53/e_teste/connect.php',
              data: JSON.stringify(tmp),

              success: function(data) {
                alert(data);
              }
            });

        });

    });
